### ISSUE TITLE
Missing attribute definition in EnumValue

### ISSUE THREAD

**Issue by pelex** [overblog/GraphQLBundle#1030]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.15.1

I have  `User Deprecated: The attributes "values" on annotation @GQL\Enum is deprecated as of 0.14 and will be removed in 1.0. Use the @GQL\EnumValue annotation on the class itself instead.` warning but can't use EnumValue as attribute. Missing attribute definition:
```
#[Attribute(Attribute::TARGET_CLASS | Attribute::IS_REPEATABLE)]
final class EnumValue extends Annotation
```

**Comment by Vincz** [comment]
Hi @pelex! It is not possible to attach annotations to constants. That's why `@GQL\EnumValue` is needed to define additional attributes (`description` or `deprecation`) on constants of the enum class.

With attributes, we can use `#[GQL\Description]` or `#[GQL\Deprecated]` directly on the constants, so the attribute `#[GQL\EnumValue]` is not needed.

To better understand, 

Check this file https://github.com/overblog/GraphQLBundle/blob/master/tests/Config/Parser/fixtures/annotations/Enum/Race.php

And this test 
https://github.com/overblog/GraphQLBundle/blob/405e83b60af3e5fdaf909473cd05cbc53fb34d03/tests/Config/Parser/MetadataParserTest.php#L240

**Comment by pelex** [comment]
Hello @Vincz , thank you for the answer. Example from this file allowed me to set all attributes correctly.
