### ISSUE TITLE
caching questions

### ISSUE THREAD

**Issue by omarsoufiane** [overblog/GraphQLBundle#130]
i didn't run a graphql app in production yet, but i would like to know if it's possible to do http caching for graphql with symfony,
normally post requests are not cachable, and symfony is heavy compared to frameworks like express, which can lead to performance issues,
 will symfony methods like $response->setSharedMaxAge(3600); work?
varnish/fastly can be configured to cache post requests, but i'm not sure if it would be a great idea.
and what about the symfony proxy ?

**Comment by mcg-web** [comment]
Hi,
This is not so easy, because a query can be write different ways to request the same data. If your graphql server doesn't have many clients you can analyze queries and override controller to add http caching... The best is to cache app level, that what recommend Facebook right now. See dataloader-bundle or dataloader-php to give you a start on this ( combine with a persistent cache system it can do the work).

**Comment by omarsoufiane** [comment]
thanks for answering. a data loader is very helpful but it depends on what kind of business logic.
the good part is that we wont need to handle cache invalidation, the negative part is scaling servers is more expensive than scaling reverse proxies,
maybe we'll have a varnish extension for graphql in the future, but still cache invalidation would be hard
