### ISSUE TITLE
"Access denied to this field." error on Query level

### ISSUE THREAD

**Issue by XavierVallot** [overblog/GraphQLBundle#322]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | x.y.z

Hello,
Querying an array of entities on a Query level with wrong access rights doesn't return the "_Access denied to this field._" error. 
All I get is an array filled with null values, which is the expected behavior, but I think I should also get the error in the response (which is the case when I query only one entity)

Here is my query : 
```yaml
Query:
  type: object
  config:
    fields:
        httpsSites:
        type: "[Site]"
        description: List of sites with https protocol
        access: "@=hasRole('ROLE_SUPER_ADMIN')"
        resolve: "@=resolver('https_sites', [value])"
```
The result with a ROLE_SUPER_ADMIN :
![image](https://user-images.githubusercontent.com/9256415/39308011-a9afa80c-4964-11e8-912b-1f155b4f61a4.png)

And with a ROLE_USER :
![image](https://user-images.githubusercontent.com/9256415/39308077-d25c1650-4964-11e8-9909-789fdf4a03fc.png)
No error, just an array of null values, why that ?

What I expect is that kind of result :
```yaml
{
  "data": {
    "httpsSites": null
  },
  "extensions": {
    "warnings": [
      {
        "message": "Access denied to this field."
      }
    ]
  }
}
```
Thanks !

**Comment by mcg-web** [comment]
Hi,

This is a normal behavior, we can't throw user error or user warning in this case cause this will set the field to null ("httpsSites" : null). But  I agree we should find a way to send error to user (using a context bag maybe?).

**Comment by XavierVallot** [comment]
Ok, thank you !

**Comment by Kocal** [comment]
Hey (@XavierVallot is my colleague), 

I know that `fields.*.access` is applied on all values of an array if the field is an array. 
So, `fields.*.access` returns `null` if the current value is not accessible.
So, it returns `httpsSites: [null, null, null, null, ...]`.

What do we want here i to returns `httpsSites: null` (or something else that is not an null-values array) plus an error message if the user has not the role `ROLE_SUPER_ADMIN`.

In order to achieve that, we tried to use a nullable-list of non-nullable site values (`type: "[Site!]"`) but it thrown an error telling us that it can not return nullables values. :thinking: 

We thought it was related to #272 because I had a similar problem a _long_ time ago, but it seems not. :confused: 

Thanks

**Comment by Kocal** [comment]
Well, maybe we can wait until (or work on) v0.12 realease :slightly_smiling_face:

**Comment by akomm** [comment]
@Kocal does something like this work for you:

```yaml
Query:
  type: object
  config:
    fields:
        httpsSites:
        type: "[Site]"
        description: List of sites with https protocol
        resolve: "@=hasRole('ROLE_SUPER_ADMIN') ? resolver('https_sites', [value]) : null"
```

This would not create access denied error message though.

My humble opinion on this:

The way I work this is actually not an issue at all. Graphql errors are in my opinion anyway often used the wrong way.

For me there is an `application / implementation` error and `user feedback`. Graphql errors should be used for the first case. If you have the case, where a resource is not accessible due to permission or other reasons, this is an expected case. If a field is `nullable`, the client should expect it to be null and accordingly display a message. For example: resource not accessible, or missiong permission. graphql errors should only come to debug, when wrong type is returned or expection thrown.

If you can not imply `null` to `permission` only, because there are domain state conditions, which make it inaccessible for other reasons than lack of permission, you should have it backed by your schema. In such cases I have something like this:

```gql
query {
  campaigns {
    capabilities {
      read {
        capable  # Boolean!
        incapableReason # String - why allowed is false
      }
    }
    # naive, simplistic example for items access, could be relay nodes, etc.
    items {id} # [Item!]
  }
}
```
With decorators you can simplify the configuration for this dramatically. 

Same applies for mutation. They return either success type or failure type. Because it is the expected possible outcome/result of the mutation. 

The only trouble I have is when 5xx codes are generated and I have to assume something went wrong.

This way client does not make any assumptions to why, it just reflects the expected. 

I instantly noticed [this issue](https://github.com/overblog/GraphQLBundle/pull/388), because my frontend reflected the correct state. Also because in some cases I got 5xx, which should not have come.

2xx with `graphql error` response is client implementation error
5xx with `graphql error` response is backend error - for example wrong type returned
5xx without `graphql error` is other backend implementation errors

My opinion, don't assasinate me please :)

**Comment by yoannrenard** [comment]
Hi guys,

I'm enduring the same issue but weirdly enough when I type `access: false` I do get my `Access denied to this field.` error but when I type  `access: "false"` I don't.

It looks like `access` needs a boolean to work.

**Comment by mcg-web** [comment]
Hi, access must be boolean for your example that the normal behavior (bool) "false" === true. Maybe we should throw an exception if not a boolean?

**Comment by Kocal** [comment]
That would be a nice improvement! 🙂

**Comment by yoannrenard** [comment]
@mcg-web Exactly! This is how yaml works and, I think, should work. 

The thing here is that when you use `access: "@=hasRole('ROLE_SUPER_ADMIN')"` it takes it as a string not as a boolean therefore the check is always true. 

FYI I'm working on an old project with a deprecated version of this bundle (0.9.x) and sf 2.8. I know shame on me :see_no_evil: 

I'll dig into it deeper tomorrow.

**Comment by mcg-web** [comment]
`@=` is a trigger to say that the string we dealing with is an expression language string. `hasRole('ROLE_SUPER_ADMIN')` will be compiled into [this php code](https://github.com/overblog/GraphQLBundle/blob/master/src/ExpressionLanguage/ExpressionFunction/Security/HasRole.php#L16 ) `$globalVariable->get('container')->get('security.authorization_checker')->isGranted('ROLE_SUPER_ADMIN');`...  This is will return a boolean not a string. This is the behavior of the bundle from the start.
