### ISSUE TITLE
Annotations config setup

### ISSUE THREAD

**Issue by tiberiu89** [overblog/GraphQLBundle#501]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12-dev

Hi, @Vincz,

I'm trying to have a complete annotation based setup. Read the docs, my goals is to have something like this
https://github.com/overblog/GraphQLBundle/blob/master/docs/annotations/arguments-transformer.md

I use custom folder structure, pointed the mappings in graphql.yaml to them.
From what I see types are generated ok in /var/cache. But I can't get annotated query/mutations to work. Usually I keep getting errors about calling method on null, which seems to come from the generated resolve field. I was thinking that maybe some service container issues, but as far as I know in symfony FQN service ids are already generated so no need to register them in services.yaml. Other then that, from the above documentation I'm still not clear if I still need a RootQuery if I'm using a provider and how are this working together. My goal is to have like UserMutations/UserQueries and so on for each section of the API, and use multiple schema.

Using symfony 4.2.

I guess a fully working setup would help here, as I feel the documentation there is missing something.

Thanks!

**Comment by Vincz** [comment]
Hey @tiberiu89 :)

The way the providers (with the `@GQL\Provider` annotation) work, is simply by adding the queries and mutations as fields on the Root Query or the Root Mutation types defined in the config. The problem is that at the moment, this Root Query & Mutation need to also be defined by annotations in order to be handle by the Annotations Parser. 

Now, the default resolver for the providers is like that : `service('<FQDN>').method(...)`. So it assumes that a public service exists in the container with the name being the name of the class. 

For example, if I put a `@GQL\Provider` on the `App\Repository\PostRepository`, this repository need to exists as a service with the name `App\Repository\PostRepository` and the service needs to be public. 

The creation of services based on class is not automatic. It is defined by config, in the services.yaml, for example:

```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Repository\:
        resource: "../../src/Repository/*"
```
So in this case, the repositories will be available as a public service with the class name as service name (I think that by default the Repository folder is excluded from the service autoconfiguration). 

I'm not sure what you mean by that 

> My goal is to have like UserMutations/UserQueries and so on for each section of the API, and use multiple schema.

But I hope this answer help. I was thinking about creating a sample projects with all the annotation features, but I need time.

**Comment by tiberiu89** [comment]
Thanks for the reply, it was useful.

It was my noob mistake, I forgot about symfony private services and that they are on by default, so that was it. Managed to run some queries.

As a side question, If cannot use providers without a root query for example, what would be the use case for providers. I assume I would use them just to group some actions together. But I guess the same can be achieved with multiple schema and endpoints.
