### ISSUE TITLE
Query parameter not detected when using jwt

### ISSUE THREAD

**Issue by belabed90** [overblog/GraphQLBundle#558]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Version/Branch   | x.y.z

When using Graphql with json web token authentificator 
the response throw an exception
"Must provide query parameter"

**Comment by murtukov** [comment]
I am using JWT on my project with GraphQL. Everything works fine.

**Comment by mcg-web** [comment]
Can you provide some more example please?

**Comment by belabed90** [comment]
Graphql was doing multiple redirects i have changed GraphqlController.php in overblog-bundle action "endpointAction" : 
this: 
```
    public function endpointAction(Request $request, string $schemaName = null)
    {
        $response = $this->createResponse($request, $schemaName, false);  
        return $response; 

    }
```
to this: 
```
    public function endpointAction(Request $request, string $schemaName = null)
    {
        $response = $this->createResponse($request, $schemaName, false);  
        $response->sendHeaders(); 
        $response->sendContent(); 
        die();
        return $response; 

    }
```

**Comment by murtukov** [comment]
@belabed90 

JWT has nothing to do with this bundle. If it says `Must provide query parameter` then you are doing something wrong.

If you still believe that this is issue of the GraphQL Bundle, then provide all of your relevant configs + the requests you are trying to perform. The best way would be to upload your project to a repository, removing all of the sensitive data.

Otherwise I'll close this issue due to lack of provided infos.

**Comment by belabed90** [comment]
Ok, i have solved this issue with the trick above, you cane close it.

Thank you !
