### ISSUE TITLE
How to map existing Schema ?

### ISSUE THREAD

**Issue by jmau111** [overblog/GraphQLBundle#606]
Hi,

thanks for this tool.
How do you map existing schema ?

I need to add a pipe to an external REST API. Setup is working fine when I define it manually in the file `Query.graphql` located in my `config/graphql/types/` folder. But when I'm trying to connect it to the API it logically throws errors.

Is there a way to describe it programmatically ?

**Comment by murtukov** [comment]
Hi @jmau111. Didn't understand your problem, could you describe it more detailed?

**Comment by jmau111** [comment]
Thanks for your answer @murtukov , my issue is I cannot find any documentation about this usage : use your graphQL bundle with an existing REST API so the graphQL would access this API.

**Comment by akomm** [comment]
There is no way for this to just work auto-magically. How and from where data is retrieved is a thing the developer has to implement and is not part of graphql's concern.

**Comment by jmau111** [comment]
@akomm well, there might be a misunderstanding. I'm just looking for ways to learn things like that, that's why I asked you if there's a documentation. I guess it's a very specific usage not covered by the bundle as you described. Thanks, again, for the tool.

**Comment by akomm** [comment]
There can at best only examples, but I don't know of any myself. Because its like documenting "programing". There are infinite way to do things. Pretty hard to do such a documentation. 

GraphQL does not care about where data comes from. GraphQL is just the query language. How you load the data to satisfy the query is up to you (to implement in a resolver). So the most naive way is to simply call an rest API in a resolver and return data. If you do not care much for efficiency/performance.

**Comment by jmau111** [comment]
@akomm ahah I'm not looking for programing advices here, it's not so rare actually to have complexe examples in documentation, Symfony does that pretty well 👍 even if people are supposed to know programing 🥇

>  If you do not care much for efficiency/performance.

The condition will not match so :)

I've been misled I guess. Not the place for these questions. Thanks for you time.
