### ISSUE TITLE
Mutation exceptions always return 200

### ISSUE THREAD

**Issue by benatespina** [overblog/GraphQLBundle#86]
Hi!

First of all, nice bundle guys! ;)

We are using it intensively in our projects and we found a bug related with exceptions catches. When we're executing a mutation and if our logic throws an exception your error handler listener builds a proper response to serve, but always returns a 200 statusCode. This is very frustrating when we consume the graphql from for example React client app, because it is not possible to discriminate for statusCode.

**Comment by mcg-web** [comment]
Hi,

We don't use http status code because in graphQL response can be partially successful. What is the code for this case?... The approach is much different than rest api because you can request many resources in a unique query... It is not recommend but if you want to use it in your app you can create a custom controller [here](https://github.com/overblog/GraphQLBundle/blob/db9124ab3c35568bfbffa190d37892d00239acfe/Controller/GraphController.php) the way was doing this at the beginning of this bundle.

**Comment by ooflorent** [comment]
Previously we were returning HTTP error codes but we found it counter-productive. GraphQL is not REST. In REST, error codes are part of the response. They have a useful meaning. In GraphQL the response is the JSON payload, not the HTTP error code.

The JS implementation has 4 possible error codes:

- `200`: everything is fine
- `400`: the GraphQL request has failed
- `405`: the HTTP request is neither `GET` nor `POST`
- `500`: unhandled server error

Maybe we could use `400` error code again. We rolled-back this change because it was causing troubles with `react-relay`.

**Comment by mcg-web** [comment]
So here come a new challenger :trollface: ! We can implement this 4 error codes in the bundle, or just give the ability of configuring them in each case :thinking:.

**Comment by benatespina** [comment]
It would be nice if we had a status code inside the error. Before "message" key for example.

**Comment by mcg-web** [comment]
we can't touch the errors format but adding http status codes like the express integration is possible. I'll try to work on a POC this week-end...

**Comment by renatomefi** [comment]
@mcg-web do you have some material/links to support this? Maybe someone else can pick this up!

**Comment by mcg-web** [comment]
just re-implementing [this](https://github.com/overblog/GraphQLBundle/blob/db9124ab3c35568bfbffa190d37892d00239acfe/Controller/GraphController.php) can be sufficient right now (with some tests to cover it)... maybe the JS implementation can help on this...

**Comment by mcg-web** [comment]
This will not be implement server side cause this conflicting with major clients like Apollo [http error](https://www.apollographql.com/docs/link/links/http.html#error). Anyway you can use [error formatting](https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/events/index.md#error-formatting) to add information to errors...
